### ISSUE TITLE
Dropdown display issue

### ISSUE THREAD

**Issue by johnyzv** [surveyjs/survey-pdf#51]
- long dropdown value does not brake line when rendering
- dropdown with other comment value that contains tab characters is not rendered well

https://plnkr.co/edit/z8P7f2T1xOW5buFw

thank you for considering this

**Comment by gologames** [comment]
Hello,

Reproduced the issue. We will investigate it and write back to this thread

Thanks, Alex
SurveyJS Team

**Comment by johnyzv** [comment]
Hello @gologames 
Any news regarding this?
Thank you,
Ionut

**Comment by ST-1580** [comment]
Hello,

We've fixed this issue via the commit above. You can set option `textFieldRenderAs: 'multiLine'` to render big texts. All this functionality will be added in the nearest update

Thanks, Yaroslav
SurveyJs Team

**Comment by johnyzv** [comment]
The issue is still reproducible, check https://plnkr.co/edit/L9Th1fj5jju8W3w6
- the text in the dropdown is truncated (everything after ".. repellat provident .. " is not displayed)
- the text in the comment box that contains "\t" caracter is not displayed

Thank you,
Ionut

**Comment by tsv2013** [comment]
Your plunker doesn't contain the recommended `textFieldRenderAs: 'multiLine',` option

**Comment by ST-1580** [comment]
Hello,

Here is [updated live sample in plunker](https://plnkr.co/edit/nBFSwU3NLV9yYnML) with option which my colleague mentioned:
![image](https://user-images.githubusercontent.com/15248977/127662887-1874af59-9dc5-4e61-92ff-92c1a1c54d8c.png)

Indeed, unfortunately, comment with `\t` character renders wrong. Seems it is another issue which doesn't related to current thread. We created [separate issue](https://github.com/surveyjs/survey-pdf/issues/65) for this. Feel free to contact us in case of any further questions

Thanks, Yaroslav
SurveyJS Team

**Comment by johnyzv** [comment]
@tsv2013 Sorry, my bad

@ST-1580 Thx, looks good, i will close this issue

All the best
